# Generated by Django 5.1.7 on 2026-07-15 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('carrera', models.CharField(blank=True, max_length=200, null=True)),
                ('no_cuenta', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('pagado', models.BooleanField(blank=True, null=True)),
                ('cartones', models.IntegerField()),
                ('entregado', models.BooleanField()),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('correo_enviado', models.BooleanField(blank=True, default=False)),
                ('entregado_por', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participantes',
            },
        ),
    ]
