# Generated by Django 5.1.7 on 2026-07-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='qr_code',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
