# Generated by Django 5.1.7 on 2026-07-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_alter_participantes_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantes',
            old_name='correo_enviado',
            new_name='mensaje_enviado',
        ),
        migrations.RemoveField(
            model_name='participantes',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='participantes',
            name='no_cuenta',
        ),
    ]
