# Generated by Django 5.1.7 on 2026-07-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_rename_correo_enviado_participantes_mensaje_enviado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantes',
            name='correo',
        ),
    ]
