# Generated by Django 5.1.7 on 2026-07-13 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0007_alter_participantes_entregado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='correo_enviado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='entregado_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
